util/ras_db.py: avoid craches due to utf-8 encoding
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/cursor.py", line 1166, in fetchone
    row = dbapi_cursor.fetchone()
sqlite3.OperationalError: Could not decode to UTF-8 column 'err_info' with text ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/sbin/ras-mc-ctl", line 93, in <module>
    main()
    ~~~~^^
  File "/usr/local/sbin/ras-mc-ctl", line 83, in main
    args.func(env_cfg, args)
    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ras_db.py", line 266, in run
    print(database.format_records(database.records(
                                  ~~~~~~~~~~~~~~~~^
        since=args.since, until=args.until, hostname=args.hostname
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )), end="")
    ^
  File "/usr/lib/python3/dist-packages/ras_db.py", line 192, in records
    for row in connection.execute(statement).mappings():
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/result.py", line 539, in iterrows
    for raw_row in self._fetchiter_impl():
                   ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/cursor.py", line 2243, in _fetchiter_impl
    row = fetchone(self, self.cursor)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/cursor.py", line 1171, in fetchone
    self.handle_exception(result, dbapi_cursor, e)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/cursor.py", line 1145, in handle_exception
    result.connection._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        err, None, None, dbapi_cursor, result.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2363, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/cursor.py", line 1166, in fetchone
    row = dbapi_cursor.fetchone()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Could not decode to UTF-8 column 'err_info' with text ''
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>